# Generated by Django 5.2.6 on 2025-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the task.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the task.')),
                ('completed', models.BooleanField(default=False, help_text='Indicates if the task is completed.')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, help_text='The date and time the task was created.'),
                ),
                (
                    'deadline_datetime_with_tz',
                    models.DateTimeField(help_text='The deadline for the task, including timezone information.'),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')],
                        default='medium',
                        help_text='The priority level of the task.',
                        max_length=10,
                    ),
                ),
            ],
            options={
                'ordering': ['deadline_datetime_with_tz', 'priority'],
            },
        ),
    ]
