# Generated by Django 5.2.6 on 2025-09-12 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(
                help_text='The user assigned to this task.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='tasks',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(
                help_text='The organization this task belongs to.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='tenant.organization',
            ),
        ),
    ]
